//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLoggerTests.LoggerSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoggerSvc.ILoggerSvc")]
    public interface ILoggerSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoggerSvc/Log", ReplyAction="http://tempuri.org/ILoggerSvc/LogResponse")]
        void Log(string message, MLogger.LogLevel logLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoggerSvc/Log", ReplyAction="http://tempuri.org/ILoggerSvc/LogResponse")]
        System.Threading.Tasks.Task LogAsync(string message, MLogger.LogLevel logLevel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoggerSvcChannel : MLoggerTests.LoggerSvc.ILoggerSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoggerSvcClient : System.ServiceModel.ClientBase<MLoggerTests.LoggerSvc.ILoggerSvc>, MLoggerTests.LoggerSvc.ILoggerSvc {
        
        public LoggerSvcClient() {
        }
        
        public LoggerSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoggerSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggerSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggerSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Log(string message, MLogger.LogLevel logLevel) {
            base.Channel.Log(message, logLevel);
        }
        
        public System.Threading.Tasks.Task LogAsync(string message, MLogger.LogLevel logLevel) {
            return base.Channel.LogAsync(message, logLevel);
        }
    }
}
